python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/人/ -s /home/lol/训练数据/加强/人/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/动物/ -s /home/lol/训练数据/加强/动物/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/格子/ -s /home/lol/训练数据/加强/格子/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/混合/ -s /home/lol/训练数据/加强/混合/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/几何/ -s /home/lol/训练数据/加强/几何/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/其它/ -s /home/lol/训练数据/加强/其它/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/素色/ -s /home/lol/训练数据/加强/素色/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/条纹/ -s /home/lol/训练数据/加强/条纹/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/网布/ -s /home/lol/训练数据/加强/网布/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/圆点/ -s /home/lol/训练数据/加强/圆点/
python run_tensorflow_get_feature.py -f /home/lol/训练数据/深度学习-布料库-加强版/植物/ -s /home/lol/训练数据/加强/植物/
